# OpenTelemetry Collector Configuration
# This configuration receives telemetry data from the Control Plane API and exports it to various backends

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024
  
  resource:
    attributes:
      - key: deployment.environment
        value: ${env:ENVIRONMENT}
        action: upsert

exporters:
  # Console exporter for debugging
  logging:
    loglevel: debug
    sampling_initial: 5
    sampling_thereafter: 200
  
  # Prometheus metrics exporter
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: controlplane
    const_labels:
      service: control-plane-api
  
  # OTLP exporter for Tempo (traces)
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  
  # Loki exporter for logs
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    tenant_id: "bpa-mvp"

service:
  pipelines:
    # Metrics pipeline
    metrics:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [prometheus, logging]
    
    # Traces pipeline
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [otlp/tempo, logging]
    
    # Logs pipeline
    logs:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [loki, logging]
