global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'bpa-mvp'
    environment: 'development'

scrape_configs:
  # Scrape metrics from OpenTelemetry Collector
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
        labels:
          service: 'control-plane-api'
  
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
