{{- if .Values.adminUI.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "business-process-agents.fullname" . }}-admin-ui
  labels:
    {{- include "business-process-agents.adminUI.labels" . | nindent 4 }}
  {{- with .Values.adminUI.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.adminUI.service.type }}
  ports:
    - port: {{ .Values.adminUI.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "business-process-agents.adminUI.selectorLabels" . | nindent 4 }}
{{- end }}
