{{- if .Values.adminUI.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "business-process-agents.fullname" . }}-admin-ui
  labels:
    {{- include "business-process-agents.adminUI.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.adminUI.replicaCount }}
  selector:
    matchLabels:
      {{- include "business-process-agents.adminUI.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "business-process-agents.adminUI.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "business-process-agents.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: admin-ui
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.adminUI.image.repository }}:{{ .Values.adminUI.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.adminUI.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            {{- range .Values.adminUI.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.adminUI.resources | nindent 12 }}
      {{- with .Values.adminUI.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.adminUI.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.adminUI.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
