{{- if and .Values.adminUI.enabled .Values.adminUI.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "business-process-agents.fullname" . }}-admin-ui
  labels:
    {{- include "business-process-agents.adminUI.labels" . | nindent 4 }}
  {{- with .Values.adminUI.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.adminUI.ingress.className }}
  ingressClassName: {{ .Values.adminUI.ingress.className }}
  {{- end }}
  {{- if .Values.adminUI.ingress.tls }}
  tls:
    {{- range .Values.adminUI.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.adminUI.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "business-process-agents.fullname" $ }}-admin-ui
                port:
                  number: {{ $.Values.adminUI.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
