{{- if and .Values.controlPlane.enabled .Values.controlPlane.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "business-process-agents.fullname" . }}-control-plane
  labels:
    {{- include "business-process-agents.controlPlane.labels" . | nindent 4 }}
  {{- with .Values.controlPlane.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.controlPlane.ingress.className }}
  ingressClassName: {{ .Values.controlPlane.ingress.className }}
  {{- end }}
  {{- if .Values.controlPlane.ingress.tls }}
  tls:
    {{- range .Values.controlPlane.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.controlPlane.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "business-process-agents.fullname" $ }}-control-plane
                port:
                  number: {{ $.Values.controlPlane.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
