{{- if .Values.controlPlane.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "business-process-agents.fullname" . }}-control-plane
  labels:
    {{- include "business-process-agents.controlPlane.labels" . | nindent 4 }}
spec:
  {{- if not .Values.controlPlane.autoscaling.enabled }}
  replicas: {{ .Values.controlPlane.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "business-process-agents.controlPlane.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/control-plane-configmap.yaml") . | sha256sum }}
      labels:
        {{- include "business-process-agents.controlPlane.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "business-process-agents.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- if and .Values.postgresql.enabled .Values.controlPlane.migration.enabled }}
        - name: db-migration
          image: "{{ .Values.controlPlane.migration.image.repository }}:{{ .Values.controlPlane.migration.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.controlPlane.image.pullPolicy }}
          command:
            - dotnet
            - ef
            - database
            - update
            - --no-build
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ConnectionStrings__DefaultConnection
              value: "{{ include "business-process-agents.postgresql.connectionString" . }}"
          resources:
            {{- toYaml .Values.controlPlane.migration.resources | nindent 12 }}
        {{- end }}
      containers:
        - name: control-plane
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.controlPlane.image.repository }}:{{ .Values.controlPlane.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.controlPlane.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: grpc
              containerPort: 8081
              protocol: TCP
          env:
            {{- range .Values.controlPlane.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            - name: ConnectionStrings__DefaultConnection
              value: "{{ include "business-process-agents.postgresql.connectionString" . }}"
            - name: ConnectionStrings__Redis
              value: "{{ include "business-process-agents.redis.connectionString" . }}"
            - name: ConnectionStrings__Nats
              value: "{{ include "business-process-agents.nats.connectionString" . }}"
          volumeMounts:
            - name: config
              mountPath: /app/appsettings.Production.json
              subPath: appsettings.Production.json
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.controlPlane.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "business-process-agents.fullname" . }}-control-plane-config
      {{- with .Values.controlPlane.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controlPlane.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controlPlane.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
