{{- if and .Values.controlPlane.enabled .Values.controlPlane.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "business-process-agents.fullname" . }}-control-plane
  labels:
    {{- include "business-process-agents.controlPlane.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "business-process-agents.fullname" . }}-control-plane
  minReplicas: {{ .Values.controlPlane.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.controlPlane.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.controlPlane.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.controlPlane.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
{{- end }}
