{{- if .Values.nats.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "business-process-agents.fullname" . }}-nats
  labels:
    {{- include "business-process-agents.labels" . | nindent 4 }}
    app.kubernetes.io/component: nats
spec:
  serviceName: {{ include "business-process-agents.fullname" . }}-nats
  replicas: 1
  selector:
    matchLabels:
      {{- include "business-process-agents.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: nats
  template:
    metadata:
      labels:
        {{- include "business-process-agents.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: nats
    spec:
      containers:
        - name: nats
          image: "{{ .Values.nats.image.repository }}:{{ .Values.nats.image.tag }}"
          imagePullPolicy: {{ .Values.nats.image.pullPolicy }}
          {{- if .Values.nats.jetstream.enabled }}
          command:
            - nats-server
            - --jetstream
            - --store_dir=/data
          {{- end }}
          ports:
            - name: client
              containerPort: 4222
              protocol: TCP
            - name: monitor
              containerPort: 8222
              protocol: TCP
          volumeMounts:
            {{- if .Values.nats.jetstream.enabled }}
            - name: data
              mountPath: /data
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: monitor
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: monitor
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.nats.resources | nindent 12 }}
  {{- if and .Values.nats.jetstream.enabled .Values.nats.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        {{- if .Values.nats.persistence.storageClass }}
        {{- if (eq "-" .Values.nats.persistence.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: {{ .Values.nats.persistence.storageClass }}
        {{- end }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.nats.persistence.size }}
  {{- else }}
      volumes:
        - name: data
          emptyDir: {}
  {{- end }}
{{- end }}
